// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/features/HomeUpgrade.tsx": () => import("../components/mockups/features/HomeUpgrade.tsx"),
  "./components/mockups/features/QuickNotes.tsx": () => import("../components/mockups/features/QuickNotes.tsx"),
  "./components/mockups/features/StudyStreak.tsx": () => import("../components/mockups/features/StudyStreak.tsx"),
  "./components/mockups/features/VideoProgress.tsx": () => import("../components/mockups/features/VideoProgress.tsx")
};
